name: studentos
description: A student productivity app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Dependencies
  #intl: ^0.19.0 # If this conflicts again, we will adjust, but try this first with clean
  intl: any
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  hive_flutter: ^1.1.0
  uuid: ^4.2.1
  google_fonts: ^6.1.0
  flutter_local_notifications: ^18.0.1
  path_provider: ^2.1.1
  
  # UPDATED: Use version 8+ to fix the Android build error
  file_picker: ^8.0.0 
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"